# Generated by Django 5.0.2 on 2024-04-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterials', 'new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studymaterials.chapter'),
        ),
    ]
