# Generated by Django 5.0.2 on 2024-04-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterials', '0001_alter_lecture_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
