# Generated by Django 5.0.2 on 2024-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('phone', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('month', models.CharField(max_length=12)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('applicable', models.BooleanField(default=True)),
                ('status', models.CharField(default='Not Paid', max_length=12)),
                ('deadilne', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
