# Generated by Django 5.0.2 on 2024-04-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='deadilne',
            new_name='deadline',
        ),
    ]
