# Generated by Django 5.0.2 on 2024-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carosel',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
