# Generated by Django 5.0.2 on 2024-02-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_alter_carosel_cimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carosel',
            name='cimage',
        ),
    ]
