# Generated by Django 5.0.2 on 2024-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_remove_carosel_cimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carosel',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
