# Generated by Django 5.0.2 on 2024-03-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
