# Generated by Django 5.0.2 on 2024-04-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_commentguest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentguest',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsguest', to='blog.post'),
        ),
    ]
